name: 🔖 Sync Org Labels

on:
  workflow_dispatch: # lancement manuel
  schedule:
    - cron: "0 3 * * 1" # chaque lundi à 03h00 UTC

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-matrix.outputs.repos }}
    steps:
      - name: Get all active repos from org (excluding forks, archived, and .github)
        id: set-matrix
        run: |
          set -euo pipefail
          echo "📡 Fetching repositories from FriendsOfFrankenPHP..."
          repos=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/FriendsOfFrankenPHP/repos \
            --paginate \
            --jq '.[] 
              | select(.archived == false and .fork == false and .name != ".github") 
              | .full_name')

          if [ -z "$repos" ]; then
            repos_json="[]"
          else
            repos_json=$(printf '%s\n' $repos | jq -R . | jq -s .)
          fi
          echo "Repos found: $repos_json"
          echo "repos=${repos_json}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}

  sync-labels:
    needs: get-repos
    if: needs.get-repos.outputs.repos != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
    steps:
      - name: Checkout org/.github repo
        uses: actions/checkout@v4

      - name: Apply labels to ${{ matrix.repo }}
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.ORG_ADMIN_TOKEN }}
          yaml-file: .github/labels.yml
          repository: ${{ matrix.repo }}
          prune: true
